// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceParkApi.DBContextModels;

namespace SpaceParkApi.Migrations
{
    [DbContext(typeof(SpaceParkDbContext))]
    [Migration("20210319214756_initialize")]
    partial class initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceParkApi.DBContextModels.ParkingRegistration", b =>
                {
                    b.Property<int>("ParkingRegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ParkingEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ParkingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ParkingSpotID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ParkingStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpaceShipName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ParkingRegistrationID");

                    b.HasIndex("ParkingSpotID");

                    b.HasIndex("UserId");

                    b.ToTable("ParkingRegistrations");
                });

            modelBuilder.Entity("SpaceParkApi.DBContextModels.ParkingSpot", b =>
                {
                    b.Property<int>("ParkingSpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("ParkingSpotID");

                    b.ToTable("ParkingSpots");
                });

            modelBuilder.Entity("SpaceParkApi.DBContextModels.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HomeWorld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SpaceParkApi.DBContextModels.ParkingRegistration", b =>
                {
                    b.HasOne("SpaceParkApi.DBContextModels.ParkingSpot", "ParkingSpot")
                        .WithMany()
                        .HasForeignKey("ParkingSpotID");

                    b.HasOne("SpaceParkApi.DBContextModels.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
